# Generated by Django 2.1.2 on 2019-06-11 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('descricao', models.TextField()),
                ('local', models.CharField(max_length=250)),
                ('hora', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaAtividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('cor_hex', models.CharField(max_length=250)),
                ('cor_nome', models.CharField(max_length=250)),
                ('cor_background', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('data', models.DateTimeField()),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField()),
                ('semana', models.CharField(max_length=3)),
                ('cronograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='conteudo.Cronograma')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('titulo', models.CharField(max_length=250)),
                ('coordenada', models.BooleanField()),
                ('descricao', models.TextField(blank=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesas', to='conteudo.Atividade')),
            ],
        ),
        migrations.CreateModel(
            name='Trabalho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('titulo', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=250)),
                ('autores', models.CharField(max_length=250)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conteudo.Evento')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabalhos', to='conteudo.Mesa')),
            ],
        ),
        migrations.AddField(
            model_name='atividade',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conteudo.CategoriaAtividade'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='dia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='conteudo.Dia'),
        ),
    ]
